on:
  push:
    tags:
    - 'v*'
name: Release
jobs:
  github-release-assets:
    name: Upload new version binaries to release assets
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build binaries in Alpine Linux
      uses: ./.github/actions/build-on-alpine
    - name: Pack binaries
      run: |
        tar -czvf darwin.tar.gz LICENSE README.md --directory=.bin/darwin .
        tar -czvf linux.tar.gz LICENSE README.md --directory=.bin/linux .
        zip windows.zip LICENSE README.md --recurse-paths --junk-paths .bin/windows
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          darwin.tar.gz
          linux.tar.gz
          windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
